name: 'Compile All LaTeX'
description: 'Searches all tex files and compiles them via Rubber'
branding:
  icon: book-open
  color: orange
inputs:
  command:
    description: The command to invoke to compile. Defaults to 'rubber --inplace -d --synctex -s'
    required: false
    default: rubber --unsafe --inplace -d --synctex -s -W all
  verbose:
    description: Adds more output
    required: false
    default: false
  success:
    description: The name of the environment variable that will hold the list of correctly compiled files. Since GitHub Actions does not support multiline output, this action writes on a variable. 
    required: false
    default: LATEX_SUCCESSES
  outputs:
    successfully-compiled:
      description: "A comma-separated list of all successfully compiled files"
    compiled-files:
      description: "A comma-separated list of all the produced pdfs"

runs:
  using: "docker"
  image: docker://danysk/compile-latex-action:1.0.45
  args:
    - ${{ inputs.command }}
    - ${{ inputs.verbose }}
    - ${{ inputs.success }}
