name: 'Compile All LaTeX'
description: 'Searches all tex files and compiles them via Rubber'
branding:
  icon: book-open
  color: orange
inputs:
  compile-command:
    description: The command to invoke to compile. Defaults to 'rubber --inplace -d --synctex -s'
    required: false
    default: rubber --unsafe --inplace -d --synctex -s
  verbose:
    description: Adds more output
    required: false
    default: true
  success-list:
    description: the file name where results will be saved
    required: false
    default: 'success-list'
runs:
  using: "docker"
  image: 'danysk/compile-latex-action'
  args:
    - ${{ inputs.compile-command }}
    - ${{ inputs.verbose }}
    - ${{ inputs.success-list }}
